server:
    port: 8888

spring:
    cloud:
        config:
            server:
                git:
                  uri: D:\programmation\multiWorkConfig


application:
    messages:
        title : This is the title of application.yml
        description : This is the description of the application.yml property file.

